# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x03\x61pp\".\n\x0fGetTermsRequest\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\",\n\x10GetTermsResponse\x12\x18\n\x05terms\x18\x01 \x03(\x0b\x32\t.app.Term\" \n\x12GetTermByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"D\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\"\'\n\x0cTermResponse\x12\x17\n\x04term\x18\x01 \x01(\x0b\x32\t.app.Term2}\n\x0fGlossaryService\x12\x37\n\x08GetTerms\x12\x14.app.GetTermsRequest\x1a\x15.app.GetTermsResponse\x12\x31\n\x0bGetTermById\x12\x17.app.GetTermByIdRequest\x1a\t.app.Termb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTERMSREQUEST']._serialized_start=23
  _globals['_GETTERMSREQUEST']._serialized_end=69
  _globals['_GETTERMSRESPONSE']._serialized_start=71
  _globals['_GETTERMSRESPONSE']._serialized_end=115
  _globals['_GETTERMBYIDREQUEST']._serialized_start=117
  _globals['_GETTERMBYIDREQUEST']._serialized_end=149
  _globals['_TERM']._serialized_start=151
  _globals['_TERM']._serialized_end=219
  _globals['_TERMRESPONSE']._serialized_start=221
  _globals['_TERMRESPONSE']._serialized_end=260
  _globals['_GLOSSARYSERVICE']._serialized_start=262
  _globals['_GLOSSARYSERVICE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
